[build]
command = "npm run build"
publish = "dist"

[[redirects]]
from = "https://www.nz-web.com/*"
to = "https://nz-web.com/:splat"
status = 301
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
